### ISSUE TITLE
in current game implementation, both buttons add 1 to player score

### ISSUE THREAD

**Issue by jakeisnt** [jakeisnt/verde#42]
one button should subtract, as the buttons are '+1' and '-1'!

**Comment by PushpenderSaini0** [comment]
This can be solved by changing `+` to a `-` on line 43 in server/game.js
```diff
- gameState: gameState + 1
+ gameState: gameState - 1
```
You can assign this to me i will submit a PR for this

**Comment by jakeisnt** [comment]
resolved with #44
